### ISSUE TITLE
Sync: Jetpack 3.9.5 and 3.9.6: Maintenance Releases

### ISSUE THREAD

**Issue by sparanoid** [sparanoid/slimpack#12]
Jetpack team just released another maintenance release, @jjloomis if you don't have time I can handle this update. :)

**Comment by jjloomis** [comment]
Hey @sparanoid. Just noticed that. I can do these updates this weekend. Something is up with my commits from my last pull request--I'm showing up as the grey Octocat and my commits aren't linking to my account. So really I want to try to resolve that issue by doing some more commits. (I think I know what caused this issue and how to fix it.) 

I may do like a chunk of 5 commits as a pull request initially. Just to see how they appear on GitHub. Is it cool with you if I do that? I want to make sure my commits are syncing up with my account again.

**Comment by sparanoid** [comment]
@jjloomis Are you using GitHub Desktop? I'm not using it so sorry I can't help you out. However It's fine to to draw the pull request with your initial commits!

**Comment by jjloomis** [comment]
Thanks @sparanoid. I think the issue happened because I tried uninstalling and reinstalling GitHub Desktop. Something got messed up in that process. I'm switching over to SourceTree.
